kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: fintrogen
  name: fintrogen
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: fintrogen
  template:
    metadata:
      labels:
        k8s-app: fintrogen
    spec:
      imagePullSecrets:
        - name: gcr-json-key

      containers:
        - name: fintrogen
          image: gcr.io/xxcloud/fintrogen:latest
          resources:
            requests:
              cpu: 0.3            
              memory: 512Mi   
            limits:
              cpu: 1            
              memory: 912Mi                               
          env:
            # - name: STORAGE_PATH
            #   value: "/tmp/public"
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: FINNHUB_KEY
              valueFrom:
                secretKeyRef:
                  name: finnhub
                  key: FINNHUB_KEY     
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 30
---
# ------------------- Dashboard Service ------------------- #
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: fintrogen
  name: fintrogen
  namespace: default
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    k8s-app: fintrogen
