kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: nitrogen
  name: nitrogen
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nitrogen
  template:
    metadata:
      labels:
        k8s-app: nitrogen
    spec:
      imagePullSecrets:
        - name: gcr-json-key

      containers:
        - name: nitrogen
          image: gcr.io/xxcloud/nitrogen
          resources:
            requests:
              cpu: 0.3            
              memory: 512Mi   
            limits:
              cpu: 1            
              memory: 912Mi                               
          env:
            # - name: STORAGE_PATH
            #   value: "/tmp/public" nitro-env
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: FINNHUB_KEY
              valueFrom:
                secretKeyRef:
                  name: finnhub
                  key: FINNHUB_KEY  

            # nitro-env
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: nitro-env
                  key: SENTRY_DSN

            - name: SENTRY_ORG
              valueFrom:
                secretKeyRef:
                  name: nitro-env
                  key: SENTRY_ORG

            - name: SENTRY_PROJECT
              valueFrom:
                secretKeyRef:
                  name: nitro-env
                  key: SENTRY_PROJECT

            - name: AMPLITUDE_KEY
              valueFrom:
                secretKeyRef:
                  name: nitro-env
                  key: AMPLITUDE_KEY

            - name: SEGMENT_PROD
              valueFrom:
                secretKeyRef:
                  name: nitro-env
                  key: SEGMENT_PROD                 
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 30
---
# ------------------- Dashboard Service ------------------- #
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: nitrogen
  name: nitrogen
  namespace: default
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    k8s-app: nitrogen
